#!/bin/bash
# Complete Railway Deployment Commands
# Copy and paste these commands one by one

echo "🚀 Railway Deployment Commands"
echo "=============================="
echo ""
echo "Run these commands in order:"
echo ""
echo "# 1. Login (opens browser)"
echo "railway login"
echo ""
echo "# 2. Initialize project"
echo "railway init"
echo ""
echo "# 3. Set environment variables"
echo "railway variables set SUPABASE_URL=YOUR_SUPABASE_URL"
echo "railway variables set SUPABASE_ANON_KEY=YOUR_SUPABASE_ANON_KEY"
echo "railway variables set SUPABASE_SERVICE_ROLE_KEY=YOUR_SUPABASE_SERVICE_ROLE_KEY"
echo "railway variables set PORT=3000"
echo "railway variables set NODE_ENV=production"
echo ""
echo "# 4. Deploy"
echo "railway up"
echo ""
echo "# 5. Get your URL"
echo "railway domain"
echo ""
echo "# 6. Test"
echo "curl https://your-url.railway.app/health"
echo ""

